## Basic Configuration

baseurl = "https://abguimba.github.io/aboutme/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishDir = "docs"
author = "Abraham Guimbao"
title = "About Me - Abraham Guimbao"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Abraham Guimbao"
intro = "Software Engineer && Student @ 42"
description = "Hello, I'm a Spanish student at 42 Paris. Since I was little I've always had a passion for software and computers. I'm currently studying, but I'm open to all kinds of opportunities. Feel free to checkout my portfolio and my CV down below."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "About Me - Abraham Guimbao"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "abguimba"
gitlab = "gitlab.com/abguimba"
linkedin = "abraham-guimbao-parra"
twitter = "abguimba"
stackoverflow = "10463714"
email = "abrahamguimbao@gmail.com"
keybase = "https://keybase.io/abguimba"

## Extras
[params.extra]
copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true

## Main Menu
[[menu.main]]
    name = "portfolio"
    weight = 100
    identifier = "portfolio"
    url = "https://abguimba.github.io"
[[menu.main]]
    name = "CV(en)"
    identifier = "CV(en)"
    weight = 200
    url = "https://abguimba.github.io/AbrahamGuimbaoCV.en.pdf"
[[menu.main]]
    name = "CV(fr)"
    identifier = "CD(fr)"
    weight = 300
    url = "https://abguimba.github.io/AbrahamGuimbaoCV.fr.pdf"
[[menu.main]]
    name = "CV(es)"
    identifier = "CD(es)"
    weight = 300
    url = "https://abguimba.github.io/AbrahamGuimbaoCV.es.pdf"
